// Code generated by protoc-gen-go-mock. DO NOT EDIT.
// versions:
// - protoc-gen-go-mock v0.0.0
// - protoc             v3.21.12
// source: example/petstore.proto

package petstore

import (
	context "context"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type PetStoreMockClient struct {
	mock.Mock
}

func NewPetStoreMockClient() *PetStoreMockClient {
	return &PetStoreMockClient{}
}

func (c *PetStoreMockClient) GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Pets, error) {
	args := c.Called(ctx, in, opts)
	return args.Get(0).(*Pets), args.Error(1)
}

func (c *PetStoreMockClient) GetPet(ctx context.Context, in *Pet, opts ...grpc.CallOption) (*Pet, error) {
	args := c.Called(ctx, in, opts)
	return args.Get(0).(*Pet), args.Error(1)
}

func (c *PetStoreMockClient) CreatePet(ctx context.Context, in *Pet, opts ...grpc.CallOption) (*Pet, error) {
	args := c.Called(ctx, in, opts)
	return args.Get(0).(*Pet), args.Error(1)
}

func (c *PetStoreMockClient) UpdatePet(ctx context.Context, in *Pet, opts ...grpc.CallOption) (*Pet, error) {
	args := c.Called(ctx, in, opts)
	return args.Get(0).(*Pet), args.Error(1)
}

func (c *PetStoreMockClient) DeletePet(ctx context.Context, in *Pet, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	args := c.Called(ctx, in, opts)
	return args.Get(0).(*emptypb.Empty), args.Error(1)
}
